### ISSUE TITLE
Model weights ? 

### ISSUE THREAD

**Issue by javiabellan** [open-vision-language/MagicLens#1]
Great work!

Do have an approximate date of when the model will be realeased ?

Thanks.

**Comment by drogozhang** [comment]
Hi,

Thanks for your interest in our work!
 
I have prepared all the code and models for release in the middle of March (>50 days ago). The main blocker is the internal check by the company. I also have no idea when or whether they will approve :( I am truly sorry about that but I have the same hope with other people in the community on the release of MagicLens.
 
I will let you know if there’s any updates and I appreciate your patience and understanding.
 
Best,
Kai

**Comment by jiashenhzju** [comment]
anything news？

**Comment by drogozhang** [comment]
Some teams approved but we are still waiting for the others (which are easier). I am more optimistic about the release :) hopefully it would be done in 1-2 weeks.

**Comment by jiashenhzju** [comment]
> Some teams approved but we are still waiting for the others (which are easier). I am more optimistic about the release :) hopefully it would be done in 1-2 weeks.

thanks, is there any plan to opensource the dataset?

**Comment by drogozhang** [comment]
I think data is not likely to be released.

**Comment by jiashenhzju** [comment]
> Some teams approved but we are still waiting for the others (which are easier). I am more optimistic about the release :) hopefully it would be done in 1-2 weeks.

anything news?

**Comment by drogozhang** [comment]
unfortunately no

**Comment by drogozhang** [comment]
@javiabellan @JerExJs The code and model are available at https://github.com/google-deepmind/magiclens

Let me know if there's any questions!

**Comment by drogozhang** [comment]
Close for inactivity, feel free to re-open it if you have any other questions.
